<?php
    $title = "Miljö- och energipolitik";
?>

<h1><?php echo $title ?></h1>
<p>Vänsterliberalerna är inte ett profilerat miljöparti, men vi tycker ändå att frågan är viktig. Dagens miljöpolitik fokuserar alltför ofta på åtgärder som kostar mycket, men har ganska liten effekt. En del av de politiska åtgärder som politikern vidtar har till och med motsatt effekt mot vad man avsåg. 

<p>Sverige har idag hög bensinskatt och hög fordonsskatt på dieselbilar. Anledningen till att dieselbilar har hög fordonsskatt påstås ofta vara det höga utsläppet av sotpartiklar, varför dieselbilar utrustade med partikelfilter har lägre fordonsskatt. Den verkliga orsaken är att de svenska bilmärkena Volvo och SAAB var sena med att utveckla dieslmotortekniken, och den svenska staten hjälpte dem därför genom att bestraffa de som köpte dieselbilar. Det högre utsläppet av partiklar märks i stadsmiljö, och bara i stadsmiljö, eftersom partiklarna bara är skadliga så länge de är i luften. Det är ett exempel på Sveriges underliga miljöpolitik. 

<p>Vad gäller bensinskatten, så motiveras den med att man dels vill få människor att byta till förnybara bränslen, dels få folk att åka mindre bil i allmänhet. När det gäller förnybara bränslen så är den krassa sanningen, att sådana finns inte på marknaden i tillräckligt hög grad för att motivera något sådant. Om du kunde hitta en etanol- eller dieselbil i gott skick för under 50 000 kr, skulle det vara en annan sak. Men så är inte fallet. De människor som inte har råd att byta till en extremsnål bil eller en miljöbil drabbas därför hårt av en hög bensinskatt. 

<p>Om man vill få folk att åka mindre bil i allmänhet, så måste man ha en väl fungerande kollektivtrafik som människor kan färdas med istället för bilen. Man behöver bara nämna SJ för att de flesta ska förstå vartåt jag syftar, men det finns fler problem. En bussbiljett mellan Uppsala och Gimo kostar 54 kronor, med rabattkort. Tur och retur blir det 108 kronor. Det är en resa på knappt 6 mil, en resa som kostar 180 kronor med en bränsletörstig bil. Det innebär att två vuxna åker bil biligare än de åker buss, med en bil som tar en liter bensin per mil. Det är en stor bil. Dessutom finns det många platser som man inte kan åka till med kollektivtrafik, och då behöver man använda ett annat fordon. Till exmpel en bil. 

<p>Vänsterliberalerna vill att Sverige ska fokusera på åtgärder som leder till att samhällets miljöbelastning minskar på riktigt, utan att samhällets minst kapitalstarka individer kommer i kläm. Det kan till exempel vara att det tas ut en skatt på alla nya bilar som säljs med en bränsleförbrukning över en liter per mil och en totalvikt under två ton, att elnätbolagen tvingas att installera en reversibel elmätare åt alla kunder som vill ha det, eller subventioner till bondgårdar som vill bygga egna biogasanläggningar. Det kan också handla om att kommuner kan söka bidrag för att bygga biogasanläggningar, att sjukhus och skolor förses med solceller på taken, eller att kommunens bilpark drivs av biogas. 

<p>Mycket av det som görs på miljö- och energiområdet sköts av privata företag, men det finns många enkla och oerhört kraftfulla åtgärder som samhället kan vidta för att både förbättra Sveriges energiläge och vår miljö. Biogas har en potential på 25 TWh per år i Sverige, bara från matavfall. Det är tillräckligt för att driva hela landets bussflotta. Om alla villapannor försågs med en generator, något som vore lönsamt för villaägare med en reversibel elmätare, skulle vi kunna få 3 TWh el per år från dem. Det är lika mycket el som samtliga vindkraftverk som finns i Sverige idag. 