<?php
	$title = "Om partiet";
?>

<h1><?php echo $title ?></h1>
<p>Alexander van Dam, Bard Nilsson och Togald Nilsson hade under en längre tid varit politiskt aktiva på olika sätt men aldrig riktigt funnit ett parti som representerade deras åsikter till fullo. Det var inte förrän i början av januari, som Alexander van Dam med det nya året och nya förhoppningar bakom sig satte sig ned och började skriva en värdegrund för ett nytt politiskt parti – ett social-liberalt parti som månade om individens frihet och rätt, samtidigt som det värnar om välfärd och trygghet. Han döpte det nya partiet till ”Ny Liberalism” med åsyftan på den individuella frihet som Nyliberalismen stod för under dess uppgång på 1700-talet, samtidigt som ”Ny” i dubbel mening syftade på en ny variant av Nyliberalism, därav särskrivningen i namnet. Partiets slagord blev ”Nya tider ger ny politik”, för allting förändras hela tiden och man måste tänka nytt och tänka om. När allt var klart skickade han ut kopior av värdegrunden till vänner och bekanta och fick ett flertal positiva svar. Mest intresserade var Bard och Togald Nilsson.

<p>Den 29:e januari 2013 träffades således dessa 3 personer på ett café i centrala Uppsala för att vidare och i detalj diskutera värdegrunden och detta nya parti. De kom snabbt överens om de olika frågorna och kände efter kvällen att de hade skapat något riktigt bra. Partiet hade då dessutom bytt namn till ”Vänsterliberalerna” efter Bards förslag, då detta namn klingade bra, låg rätt i munnen, var lätt att komma ihåg samt direkt gav insikt i vad för typ av politik partiet driver.

<p>Folkpartiet hade länge varit det enda liberala partiet, men kändes inte attraktivt för någon av dem eftersom Folkpartiet mer eller mindre saknade hela delen med social trygghet, och samarbetade med Moderaterna vars slagord "Arbeit macht frei" (som det blir översatt till tyska) beskriver deras syn på samhällets svagare individer ganska bra. Individer som inte kan jobba för att de är sjuka, eller som inte får något jobb för att samhällets utbildningssystem har drabbats av en bugg. För att fylla detta tomrum startades Vänsterliberalerna, ett liberalt parti med en stark tro på att även ett modernt, individualistiskt och fritt samhälle behöver ett socialt skyddsnät om det skulle gå åt helvete i livet. Olyckan kan drabba alla, fattig som rik, och om vi alla hjälps åt så kan även de som drabbats av olyckan få chansen att leva ett drägligt liv.

<p>Samtidigt är Vänsterliberalernas tro på individens rätt och frihet mycket stor. Vi tycker att alla människor ska ha rätt att leva sitt liv fritt, utan att övervakas mot sin vilja, utan att utsättas för rättsövergrepp, utan att råka ut för våldsbrott eller andra former av kriminalitet eller att bli diskriminerade för utséende, sexuell läggning eller religiös/filosofisk övertygelse. Därför är vi i partiet heller inte rädda för att visa vilka vi är och säga vad vi tycker – även om vissa saker kan anses otroligt kontroversiella, i alla fall innan vi har förklarat helheten bakom vårt utlåtande. Vi är övertygade om att det är möjligt att ha ett samhälle där individen har stor individuell frihet, utan att vi för den sakens skull måste underlåta att ge de människor som inte har så gott om pengar eller svårigheter att kommunicera rätt till sjukvård, god levnadsstandard och utbildning.