<?php
    $title = "Fakta och saklighet";
?>

<h1><?php echo $title ?></h1>
<p>Många frågor inom politik saknar faktaunderlag. Man kan inte veta om kommunism i en demokrati är dåligt eller inte, för det är ännu ingen som har provat. Och det är för dyrt för att någon ska vilja göra det. Men i många andra frågor, så finns det forskning, exempel, statistiska underlag eller andra mer eller mindre pålitliga källor som man kan granska, för att kontrollera om en politisk linje är rimlig eller inte. Och Vänsterliberalerna anser, att om det finns forskning inom ett politiskt område, så är det politikernas ansvar att ta hänsyn till de resultat som forskningen kommit fram till. 

<p>Att bara debattera med vad man tycker, utan att luta sig på någon fakta, leder oftast ingen vart. Och att fatta beslut i riksdagen baserat på medieklimatet, eller bara vad man tycker passar bäst in i partiets linje just nu, håller inte i längden. Man måste, om det är möjligt, försöka hålla sig till sakliga argument och fakta. Det är till exempel ingen som har kunnat visa att illegal fildelning gör att musikartister, spelskapare och filmskapare förlorar pengar, trots att det är det vanligaste argumentet mot illegal fildelning. Vad man har kunnat visa, är att de som säljer skivorna förlorar pengar på illegal fildelning. Men det är inte nödvändigtvis samma sak. Tvärtom har man i rapport efter rapport kommit fram till att kulturskapare faktiskt tjänar på illegal fildelning. EU-kommissionen är en av de som släppt en sådan rapport. 

<p>Tyvärr är det ofta så det ser ut i debatten idag. Det vanligaste argumentet för att ha kärnkraft i Sverige är att man påstår att de förnybara energikällorna inte har tillräckligt stor potential. Vilket är rent skitsnack och går att motbevisa på fem minuter med papper, penna och lite data från Wikipedia. Man har inte lyckats bevisa att det finns något samband mellan våldstendenser hos ungdomar och dator/TV-spelande, men trots det var debatten livlig för bara ett decennium sedan. Vi har väldigt hög bensinskatt i Sverige, vilket motiveras dels med att man vill få människor att åka kollektivt, dels med att man vill få folk att välja snålare bilar. Båda dessa argument faller, eftersom kollektivtrafik trots dyr bensin i många fall är dyrare än att åka bil, och eftersom Sverige även har en av europas äldsta och bränsletörstigaste bilparker. 

<p>Vänsterliberalerna vill att politikerna blir mer sakliga i debatten, och förhåller sig till fakta istället för opinionssiffror när beslut ska fattas. Opinionsmätningarna har ofta flera procentenheters felmariginal, och tenderar att ändras snabbt med tiden. Fakta är mer beständig, och att hålla sig till fakta innebär att man kan fatta beslut som får den effekt man önskat, istället för att bara förbättra partiets opinionssiffror några veckor framåt. 